/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Course;
import BackEnd.Student;
import BackEnd.User;
import FrontEnd.StudentDashboard;
import Services.StudentService;
import databse.JsonDatabaseManager;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class EnrollCourse extends javax.swing.JPanel {

    private StudentDashboard parentDashboard;
    private String studentId;
    private JsonDatabaseManager dbManager;
    private StudentService studentService;
    
    public EnrollCourse(JsonDatabaseManager dbManager, String studentId, StudentDashboard parentDashboard) {
        initComponents();
        this.dbManager = dbManager;
        this.studentId = studentId;
        this.parentDashboard = parentDashboard;

        
        User currentUser = dbManager.getUserById(studentId);
        if (currentUser instanceof Student) {
            this.studentService = new StudentService(dbManager, (Student) currentUser);
        } else {
            throw new IllegalArgumentException("User is not a student");
        }

        loadCourses();
    }


   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        enroll = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Course Id", "Course Name", "Instructor", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Enroll Courses");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        enroll.setBackground(new java.awt.Color(204, 204, 204));
        enroll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enroll.setForeground(new java.awt.Color(102, 102, 255));
        enroll.setText("enroll");
        enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enroll)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(enroll)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void enrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a course first.");
            return;
        }
        String courseId = jTable1.getValueAt(selectedRow, 0).toString();
        boolean success = studentService.enrollInCourse(courseId);
        if (success) {
            JOptionPane.showMessageDialog(this, "Enrolled successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "Enrollment failed or already enrolled.");
        }
    }//GEN-LAST:event_enrollActionPerformed
    private void loadCourses() {
        var courses = studentService.browseAvailableCourses();
        String[] columns = {"Course ID", "Title", "Instructor", "Description"};
        Object[][] data = new Object[courses.size()][4];
        int i = 0;
        for (Course c : courses) {
            data[i][0] = c.getCourseId();
            data[i][1] = c.getTitle();
            data[i][2] = c.getInstructorId();
            data[i][3] = c.getDescription();
            i++;
        }
        jTable1.setModel(new DefaultTableModel(data, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
