/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;


    import Services.StudentService;
    import BackEnd.Course;
    import FrontEnd.Lessons;
    import java.awt.CardLayout;
    import java.util.List;
    import javax.swing.JOptionPane;
    import javax.swing.table.DefaultTableModel;
    import javax.swing.JPanel;


import Services.CertificateService;                         // lab8//
import BackEnd.Certificate;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.File;                                        // lab8 //
import javax.swing.JButton;



public class EnrolledCourses extends javax.swing.JPanel {

    private StudentDashboard parentDashboard;
    private StudentService studentService;
    private CertificateService certificateService;    //lab8//
    
     public EnrolledCourses(StudentDashboard parentDashboard) {
        initComponents();
        this.parentDashboard = parentDashboard;
        this.studentService = parentDashboard.getStudentService();
        this.certificateService= new CertificateService(this.parentDashboard.getDbManager());
        loadEnrolledCourses();
        setupListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Load = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Enrolled Courses");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Course Id", "Course Name", "Instructor", "Description", "statues", "Certificate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Load.setBackground(new java.awt.Color(204, 204, 204));
        Load.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Load.setForeground(new java.awt.Color(102, 102, 255));
        Load.setText("Load");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 667, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Load)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Load)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        // TODO add your handling code here:
  
        loadEnrolledCourses();
    }//GEN-LAST:event_LoadActionPerformed

 private void loadEnrolledCourses() {
    List<Course> enrolled = studentService.viewEnrolledCourses();

    String[] columnNames = {"Course ID", "Course Name", "Instructor", "Description", "Status", "Certificate"};
    Object[][] data = new Object[enrolled.size()][6];

    for (int i = 0; i < enrolled.size(); i++) {
        Course c = enrolled.get(i);
        data[i][0] = c.getCourseId();
        data[i][1] = c.getTitle();
        data[i][2] = c.getInstructorId();
        data[i][3] = c.getDescription();
        
        String studentID = parentDashboard.getStudentId();
        
        if (!certificateService.isCourseCompleted(studentID, c.getCourseId())) {
            data[i][4] = "In progress";
            data[i][5] = "N/A";
        } else {
            data[i][4] = "Certificate Earned - Click to View";
            data[i][5] = c.getCourseId();
        }
    }

    DefaultTableModel model = new DefaultTableModel(data, columnNames) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    jTable1.setModel(model);
}

// Modify your setupListeners method to handle certificate clicks
private void setupListeners() {
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = jTable1.getSelectedRow();
            int column = jTable1.getSelectedColumn();
            
            if (row >= 0) {
                if (column == 4) { // Status column
                    String status = jTable1.getValueAt(row, 4).toString();
                    if (status.contains("Certificate Earned")) {
                        String courseId = jTable1.getValueAt(row, 0).toString();
                        showCertificateOptions(courseId);
                    }
                } else if (column == 0) { // Course ID column - double click for lessons
                    if (evt.getClickCount() == 2) {
                        String courseId = jTable1.getValueAt(row, 0).toString();
                        Lessons lesson = parentDashboard.getLessonPanel(courseId);
                        lesson.loadlessons(courseId);
                        
                        CardLayout cl = (CardLayout) parentDashboard.getContentPanel().getLayout();
                        cl.show(parentDashboard.getContentPanel(), "lesson");
                    }
                }
            }
        }
    });
}

private void showCertificateOptions(String courseId) {
    String[] options = {"View Certificate", "Download Certificate", "Cancel"};
    int choice = JOptionPane.showOptionDialog(this,
            "Choose an action for the certificate:",
            "Certificate Options",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.INFORMATION_MESSAGE,
            null,
            options,
            options[0]);
    
    switch (choice) {
        case 0:
            viewCertificate(courseId);
            break;
        case 1:
            downloadCertificate(courseId);
            break;
        default:
            break;
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Load;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
 
//lab8//
    
 private void addCertificateButtons()
 {
     for(int i=0;i<jTable1.getRowCount();i++)
     {
         String statues = jTable1.getValueAt(i, 4).toString();
         
         if(statues.equals("Certificate Earned"))
         {
             String CourseID=jTable1.getValueAt(i, 0).toString();
             
             JPanel buttonPanel=new JPanel();
             
             JButton viewButton=new JButton("view");
             viewButton.addActionListener(e-> viewCertificate(CourseID));
             
             JButton downloadButton = new JButton("download");
             downloadButton.addActionListener(e-> downloadCertificate(CourseID));
             
             buttonPanel.add(viewButton);
             buttonPanel.add(downloadButton);
             
             jTable1.setValueAt(buttonPanel, i, 5);
       
         }
     }
     

     
 }

 private void viewCertificate(String Cid)
 {
    try{
        
        String studentID=this.parentDashboard.getStudentId();
        Certificate cert = certificateService.GenerateCertificate(studentID, Cid);
        
        if(cert!=null)
        {
            certificateService.StoreCertificate(cert);
            ObjectNode JsonCert=certificateService.ConvertCertificateToJSON(cert);
            
            String certText=String.format("CERTIFICATE OF COMPLETION\n\nstudent:%s\ncourse:%s\ncertificateId:%s",studentID,Cid,cert.getCertificateID());
            
            JOptionPane.showMessageDialog(this,certText,"Certificate",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }
     catch(Exception e)
     { 
        JOptionPane.showMessageDialog(this,"Error:"+e.getMessage());
     }
      
 }
 
 
 private void downloadCertificate(String Cid)
 {
      try{
        
        String studentID=this.parentDashboard.getStudentId();
        Certificate cert = certificateService.GenerateCertificate(studentID, Cid);
        
        if(cert!=null)
        {
            certificateService.StoreCertificate(cert);
            ObjectNode JsonCert=certificateService.ConvertCertificateToJSON(cert);
            ObjectMapper mapper = new ObjectMapper();
            String filename = "Certificate_"+cert.getCertificateID()+".json";
            File file = new File(filename);
            mapper.writerWithDefaultPrettyPrinter().writeValue(file,JsonCert);
            
            JOptionPane.showMessageDialog(this,"Saved: "+filename);
            
        }
      }
      
     catch(Exception e)
     { 
        JOptionPane.showMessageDialog(this,"Error:"+e.getMessage());
     }
      
      
     
     
     
 }
    
}
