/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Lesson;
import Services.CourseService;
import Services.QuizService;
import Services.StudentService;
import java.awt.CardLayout;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;;

public class Lessons extends javax.swing.JPanel {

    private StudentDashboard parentDashboard;
    private CourseService courseService;
    private QuizService quizService;
     private StudentService studentService;
     
   private String courseId1;

    private JTextField courseIdField;
    private JButton loadButton;
    private JButton backButton;
    private JTable lessonTable;
    private JScrollPane tableScroll;

    public Lessons(StudentDashboard parentDashboard, CourseService courseService, StudentService studentService, String courseId1) {
        this.parentDashboard = parentDashboard;
        this.courseService = courseService;
        this.studentService = studentService;
        this.quizService = new QuizService(parentDashboard.getDbManager());
        this.courseId1=courseId1;
        initComponents();
        setupListeners(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Load = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Access Lessons");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Lesson Id", "Title", "Status", "pass/fail", "best score"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        Load.setBackground(new java.awt.Color(204, 204, 204));
        Load.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Load.setForeground(new java.awt.Color(102, 102, 255));
        Load.setText("Load Lessons");
        Load.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Progress");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Back.setBackground(new java.awt.Color(204, 204, 204));
        Back.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Back.setForeground(new java.awt.Color(102, 102, 255));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Load)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(185, 185, 185)
                                .addComponent(Back)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Back)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Load)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadActionPerformed
        // TODO add your handling code here:
         loadlessons(courseId1);
    }//GEN-LAST:event_LoadActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
     CardLayout cl = (CardLayout) parentDashboard.getContentPanel().getLayout();
       cl.show(parentDashboard.getContentPanel(), "enrolled");
    }//GEN-LAST:event_BackActionPerformed

     
 
 
private void setupListeners() {

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getClickCount() == 2) { 
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    String lessonId = jTable1.getValueAt(row, 0).toString();
               
                    LessonContent lessonContent = parentDashboard.getLessonContentPanel();
                    if (lessonContent == null) {
                        JOptionPane.showMessageDialog(Lessons.this, 
                            "Lesson content panel not available. Please try again.");
                        return;
                    }
                    
                    lessonContent.loadLesson(courseId1, lessonId);
                    
                    CardLayout cl = (CardLayout) parentDashboard.getContentPanel().getLayout();
                    cl.show(parentDashboard.getContentPanel(), "lessonContent");
                }
            }
        }
    });
}

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Load;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

   
    void loadlessons(String courseid) {
        List<Lesson> lessons = courseService.getCourseLessons(courseid);
        List<String> status = studentService.getCompletedLessons(courseid);
        
        Object[][] data = new Object[lessons.size()][5]; 
        for (int i = 0; i < lessons.size(); i++) {
            Lesson currentLesson = lessons.get(i);
            String currentLessonId = currentLesson.getLessonId();
            
            data[i][0] = currentLessonId;
            data[i][1] = currentLesson.getTitle();
          
            if(status.contains(currentLessonId)) {
                data[i][2] = "Completed";
            } else {
                data[i][2] = "Incomplete";
            }
            if (currentLesson.getQuiz() != null) {
                String quizId = currentLesson.getQuiz().getQuizID();
                Double bestScore = quizService.getBestScore(parentDashboard.getStudentId(), quizId);
                
                if (bestScore != null) {
                    data[i][3] = bestScore >= 50 ? "Pass" : "Fail";
                    data[i][4] = String.format("%.1f%%", bestScore);
                } else {
                    data[i][3] = "Not Taken";
                    data[i][4] = "N/A";
                }
            } else {
                data[i][3] = "No Quiz";
                data[i][4] = "N/A";
            }
        }
        
        DefaultTableModel model = new DefaultTableModel(data, 
            new String[]{"Lesson ID", "Title", "Status", "Pass/Fail", "Best Score"}) {
            @Override
            public boolean isCellEditable(int row, int column) { 
                return false; 
            }
        };
        
        double progress = studentService.getCourseProgress(courseid);
        String progressFormat = String.format("%.2f", progress);
        jTable1.setModel(model); 
        jLabel2.setText("Progress : "+ progressFormat+"%" );
    }

    }

