/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package FrontEnd;

import BackEnd.Quiz;
import Quiz.Question;
import Quiz.StudentAnswer;
import Quiz.QuizAttempt;
import Services.QuizService;
import Utils.IdGenerator;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

public class QuizPanel extends javax.swing.JPanel {

    private QuizService quizService;
    
    private Quiz currentQuiz;
    private String currentCourseId;
    private String currentLessonId;
    private String studentId;
    
    private List<Question> questions;
    private List<StudentAnswer> studentAnswers;
    private int currentQuestionIndex = 0;
    private boolean showAnswers = false;
    private int remainingAttempts;
    private StudentDashboard parentDashboard;
            
      public QuizPanel(StudentDashboard parentDashboard) {
       
        this.parentDashboard = parentDashboard;
        this.quizService = new QuizService(parentDashboard.getDbManager());
        this.studentId = parentDashboard.getStudentId();
        this.studentAnswers = new ArrayList<>();
        
     initComponents();
       
    }
      public void loadQuiz(String courseId, String lessonId, BackEnd.Quiz quiz) {
        this.currentCourseId = courseId;
        this.currentLessonId = lessonId;
        this.currentQuiz = quiz;
        this.questions = quiz.getQuestions();
        this.currentQuestionIndex = 0;
        this.studentAnswers.clear();
        this.showAnswers = false;
        

        this.remainingAttempts = quizService.getRemainingAttempts(studentId, quiz.getQuizID());
        if (remainingAttempts <= 0) {
            showNoAttemptsMessage();
            return;
        }
        
        for (int i = 0; i < questions.size(); i++) {
            studentAnswers.add(null);
        }
        
        showQuestion();
    }
        
         private void showNoAttemptsMessage() {
        Ttile.setText("No Attempts Remaining");
        jTextArea1.setText("You have used all your attempts for this quiz.\n\n" +
                          "Maximum attempts: " + currentQuiz.getMaxAttempts() + "\n" +
                          "Your attempts: " + getUsedAttemptsCount() + "\n\n" +
                          "Please contact your instructor if you need additional attempts.");
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jComboBox1.setVisible(false);
        Submit1.setVisible(false);
        Next.setVisible(false);
        Previous.setVisible(false);
        
        revalidate();
        repaint();
    }
private int getUsedAttemptsCount() {
        return currentQuiz.getMaxAttempts() - remainingAttempts;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ttile = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        Previous = new javax.swing.JButton();
        Submit1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();

        Ttile.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        Ttile.setForeground(new java.awt.Color(102, 102, 255));
        Ttile.setText("Title");
        Ttile.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ttile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Next.setBackground(new java.awt.Color(204, 204, 204));
        Next.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Next.setForeground(new java.awt.Color(102, 102, 255));
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });

        Previous.setBackground(new java.awt.Color(204, 204, 204));
        Previous.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Previous.setForeground(new java.awt.Color(102, 102, 255));
        Previous.setText("Previous");
        Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousActionPerformed(evt);
            }
        });

        Submit1.setBackground(new java.awt.Color(204, 204, 204));
        Submit1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Submit1.setForeground(new java.awt.Color(102, 102, 255));
        Submit1.setText("Submit");
        Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(Ttile))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Previous, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(Next, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(Submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Ttile)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Next)
                    .addComponent(Previous)
                    .addComponent(Submit1))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
        // TODO add your handling code here:
            saveCurrentAnswer();
            currentQuestionIndex++;
            showQuestion();
    }//GEN-LAST:event_NextActionPerformed

    private void PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousActionPerformed
        // TODO add your handling code here:
        saveCurrentAnswer();
        currentQuestionIndex--;
        showQuestion();

    }//GEN-LAST:event_PreviousActionPerformed

    private void Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1ActionPerformed
        // TODO add your handling code here:
        if (Submit1.getText().equals("Submit Quiz")) {
            submitQuiz();
        }
      
        }


    {      
    }//GEN-LAST:event_Submit1ActionPerformed
 private void showQuestion() {
    if (currentQuestionIndex >= questions.size()) {
      
        calculateAndShowResults();
        return;
    }
    
    Question currentQuestion = questions.get(currentQuestionIndex);
   
    Ttile.setText("Question " + (currentQuestionIndex + 1) + " of " + questions.size() + 
                 " (Attempts: " + remainingAttempts + " remaining)");
    jTextArea1.setText(currentQuestion.getContent());
    jTextArea1.setLineWrap(true);
    jTextArea1.setWrapStyleWord(true);
   
    jComboBox1.removeAllItems();
    jComboBox1.addItem("-- Select Answer --");
    for (String option : currentQuestion.getOptions()) {
        jComboBox1.addItem(option);
    }
    
    StudentAnswer previousAnswer = studentAnswers.get(currentQuestionIndex);
    if (previousAnswer != null) {
        jComboBox1.setSelectedItem(previousAnswer.getStudentAnswer());
    } else {
        jComboBox1.setSelectedIndex(0);
    }
   
    Previous.setEnabled(currentQuestionIndex > 0);
    
    if (currentQuestionIndex == questions.size() - 1) {
        Next.setVisible(false);
        Submit1.setVisible(true);
        Submit1.setText("Submit Quiz");
        
        for (java.awt.event.ActionListener al : Submit1.getActionListeners()) {
            Submit1.removeActionListener(al);
        }
        Submit1.addActionListener(evt -> submitQuiz());
    } else {
        Next.setVisible(true);
        Submit1.setVisible(false);
    }

    jComboBox1.setVisible(true);
    Previous.setVisible(true);
    
    revalidate();
    repaint();
}
     private void calculateAndShowResults() {
   
    if (studentAnswers != null && !studentAnswers.isEmpty()) {
        String attemptId = new IdGenerator().generateAttemptId();
        QuizAttempt attempt = new QuizAttempt(attemptId, studentId, currentQuiz.getQuizID(), 0, 
                                            new ArrayList<>(studentAnswers));
        double score = currentQuiz.evaluate(attempt);
        showResults(score);
    } else {
        
        showResults(0.0);
    }
}


     private void saveCurrentAnswer() {
        String selectedAnswer = (String) jComboBox1.getSelectedItem();
        if (selectedAnswer == null || selectedAnswer.equals(" -- Select Answer -- ")) {
        return; 
    }

    Question currentQuestion = questions.get(currentQuestionIndex);
    
    boolean isAnswerCorrect = currentQuestion.checkAnswer(selectedAnswer); 

    

    StudentAnswer newAnswer = new StudentAnswer(
        currentQuestion, 
        selectedAnswer, 
        isAnswerCorrect 
    );
    
    if (currentQuestionIndex < studentAnswers.size()) {
        studentAnswers.set(currentQuestionIndex, newAnswer); 
    } else {
        studentAnswers.add(newAnswer);
    }
}

     private void showResults(double score) {
    Ttile.setText("Quiz Results");
    
    JTabbedPane tabbedPane = new JTabbedPane();
    
    JPanel summaryPanel = new JPanel(new BorderLayout());
    JTextArea summaryText = new JTextArea();
    summaryText.setEditable(false);
    summaryText.setLineWrap(true);
    summaryText.setWrapStyleWord(true);
    
    String summary = String.format(
        "Quiz: %s\n\n" +
        "Your Score: %.1f%%\n" +
        "Status: %s\n" +
        "Passing Score: 50%%\n" +
        "Maximum Attempts: %d\n\n" +
        "%s",
        currentQuiz.getName(),
        score,
        (score >= 50) ? "PASSED ✓" : "FAILED ✗",
        remainingAttempts,
        currentQuiz.getMaxAttempts(),
        (score >= 50) ? "Congratulations! You have passed this quiz." :
                       "You can try again if you have remaining attempts."
    );
    summaryText.setText(summary);
    summaryPanel.add(new JScrollPane(summaryText), BorderLayout.CENTER);
    
    JPanel buttonPanel = new JPanel(new FlowLayout());
    JButton showAnswersBtn = createShowAnswersButton();
    buttonPanel.add(showAnswersBtn);
    summaryPanel.add(buttonPanel, BorderLayout.SOUTH);
    
    tabbedPane.addTab("Summary", summaryPanel);

    JPanel answersPanel = createDetailedAnswersPanel();
    tabbedPane.addTab("Detailed Review", answersPanel);
    

    removeAll();
    setLayout(new BorderLayout());
    
    JPanel topPanel = new JPanel(new BorderLayout());
    topPanel.add(Ttile, BorderLayout.WEST);
    
    JButton backButton = new JButton("Back to Lesson");
    backButton.addActionListener(e -> goBackToLesson());
    topPanel.add(backButton, BorderLayout.EAST);
    
    add(topPanel, BorderLayout.NORTH);
    add(tabbedPane, BorderLayout.CENTER);
    
    revalidate();
    repaint();
    
    if (score >= 50) {
        JOptionPane.showMessageDialog(this, 
            "Congratulations! You passed the quiz with " + String.format("%.1f", score) + "%", 
            "Quiz Passed", 
            JOptionPane.INFORMATION_MESSAGE);
    }
}
     private void showAllAnswers() {
        StringBuilder answersText = new StringBuilder();
        answersText.append("Quiz Answers:\n\n");
        
        for (int i = 0; i < questions.size(); i++) {
            Question question = questions.get(i);
            StudentAnswer studentAnswer = studentAnswers.get(i);
            
            answersText.append("Question ").append(i + 1).append(":\n");
            answersText.append(question.getContent()).append("\n");
            answersText.append("Correct Answer: ").append(question.getCorrectAnswer()).append("\n");
            
            String studentAnswerText = studentAnswer != null ? studentAnswer.getStudentAnswer() : "Not answered";
            boolean isCorrect = studentAnswer != null && studentAnswer.isCorrect();
            
            answersText.append("Your Answer: ").append(studentAnswerText);
            answersText.append(isCorrect ? " ✓\n" : " ✗\n");
            answersText.append("\n");
        }
        
        Ttile.setText("Quiz Answers");
        jTextArea1.setText(answersText.toString());
        
        Submit1.setText("Back to Lesson");
        Submit1.setVisible(true);
       
        for (java.awt.event.ActionListener al : Submit1.getActionListeners()) {
            Submit1.removeActionListener(al);
        }
        Submit1.addActionListener(evt -> goBackToLesson());
        
        revalidate();
        repaint();
    }

    private void goBackToLesson() {
           removeAll();
    initComponents();
    
    LessonContent lessonContent = parentDashboard.getLessonContentPanel();
    if (lessonContent != null) {
        lessonContent.loadLesson(currentCourseId, currentLessonId);
    }
      CardLayout cl = (CardLayout) parentDashboard.getContentPanel().getLayout();
    cl.show(parentDashboard.getContentPanel(), "lessonContent");;
    }

    public QuizPanel() {
        initComponents();
    }
    
     private void submitQuiz() {
   
    saveCurrentAnswer();
 
    boolean allAnswered = true;
    List<Integer> unansweredQuestions = new ArrayList<>();
    
    for (int i = 0; i < questions.size(); i++) {
        if (studentAnswers.get(i) == null) {
            allAnswered = false;
            unansweredQuestions.add(i + 1);
        }
    }
    
    if (!allAnswered) {
        String message = "Please answer all questions before submitting.\n" +
                        "Unanswered questions: " + unansweredQuestions;
        JOptionPane.showMessageDialog(this, message, 
            "Incomplete Quiz", JOptionPane.WARNING_MESSAGE);
        return;
    }
   
    int currentRemainingAttempts = quizService.getRemainingAttempts(studentId, currentQuiz.getQuizID());
    if (currentRemainingAttempts <= 0) {
        JOptionPane.showMessageDialog(this, 
            "You have no attempts remaining for this quiz.",
            "No Attempts Remaining", JOptionPane.ERROR_MESSAGE);
        return;
    }
   
    int confirm = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to submit the quiz?\nThis will use one of your attempts.",
        "Confirm Quiz Submission", JOptionPane.YES_NO_OPTION);
    
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }
    
    try {
        String attemptId = new IdGenerator().generateAttemptId();
        QuizAttempt attempt = new QuizAttempt(attemptId, studentId, 
            currentQuiz.getQuizID(), 0, new ArrayList<>(studentAnswers));
        
        boolean submitted = quizService.submit(attempt);
       
        if (submitted) {
            double score = currentQuiz.evaluate(attempt);
            showResults(score); 
        } else {
            JOptionPane.showMessageDialog(this, 
                "Failed to submit quiz. Please try again.",
                "Submission Failed", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error submitting quiz: " + e.getMessage(),
            "Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    
    
}

     private JButton createShowAnswersButton() {
    JButton showAnswersBtn = new JButton("Show Answers");
    showAnswersBtn.setBackground(new Color(102, 102, 255));
    showAnswersBtn.setForeground(Color.WHITE);
    showAnswersBtn.setFont(new Font("Segoe UI", Font.BOLD, 14));
    showAnswersBtn.addActionListener(e -> showAllAnswers());
    return showAnswersBtn;
}
     
     private JPanel createDetailedAnswersPanel() {
    JPanel answersPanel = new JPanel(new BorderLayout());
    JTextArea answersText = new JTextArea();
    answersText.setEditable(false);
    answersText.setLineWrap(true);
    answersText.setWrapStyleWord(true);
    
    StringBuilder answersBuilder = new StringBuilder();
    int correctCount = 0;
    
    for (int i = 0; i < questions.size(); i++) {
        Question question = questions.get(i);
        StudentAnswer studentAnswer = studentAnswers.get(i);
        String studentAnswerText = (studentAnswer != null) ? studentAnswer.getStudentAnswer() : "Not answered";
        boolean isCorrect = (studentAnswer != null) && studentAnswer.isCorrect();
        
        if (isCorrect) correctCount++;
        
        answersBuilder.append(String.format("Question %d:\n", i + 1));
        answersBuilder.append(String.format("Question: %s\n", question.getContent()));
        answersBuilder.append(String.format("Your answer: %s %s\n", 
            studentAnswerText, isCorrect ? "✓" : "✗"));
        answersBuilder.append(String.format("Correct answer: %s\n", question.getCorrectAnswer()));
        answersBuilder.append(String.format("Options: %s\n", String.join(", ", question.getOptions())));
        answersBuilder.append("―".repeat(50) + "\n\n");
    }
    
    answersBuilder.insert(0, String.format("You got %d out of %d questions correct.\n\n", correctCount, questions.size()));
    answersText.setText(answersBuilder.toString());
    answersPanel.add(new JScrollPane(answersText), BorderLayout.CENTER);
    
    return answersPanel;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JButton Previous;
    private javax.swing.JButton Submit1;
    private javax.swing.JLabel Ttile;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
