/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

import BackEnd.Student;
import Services.CourseService;
import Services.StudentService;
import Services.UserService;
import databse.JsonDatabaseManager;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;

public class StudentDashboard extends javax.swing.JFrame {

    private CardLayout cardLayout;

    private String studentId;
    private JsonDatabaseManager dbManager;
    private StudentService studentService;
    private Student currentStudent;

    private Lessons LessonPanel;
    private LessonContent lessonContentPanel;
    private CourseService courseService;
    private QuizPanel quizPanel;

    public StudentDashboard(JsonDatabaseManager dbManager, String studentId) {
        this.studentId = studentId;
        this.dbManager = dbManager;
        this.currentStudent = (Student) dbManager.getUserById(studentId);
        this.studentService = new StudentService(dbManager, currentStudent);
        this.courseService = new CourseService(dbManager); 

        initComponents();
        initCards(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        Enroll = new javax.swing.JButton();
        ViewCourses1 = new javax.swing.JButton();
        Enroll1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        contentPanel = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Enroll.setBackground(new java.awt.Color(153, 153, 255));
        Enroll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Enroll.setForeground(new java.awt.Color(255, 255, 255));
        Enroll.setText("Enroll in a Course");
        Enroll.setBorderPainted(false);
        Enroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnrollActionPerformed(evt);
            }
        });

        ViewCourses1.setBackground(new java.awt.Color(153, 153, 255));
        ViewCourses1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ViewCourses1.setForeground(new java.awt.Color(255, 255, 255));
        ViewCourses1.setText("View Availble Courses");
        ViewCourses1.setBorderPainted(false);
        ViewCourses1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCourses1ActionPerformed(evt);
            }
        });

        Enroll1.setBackground(new java.awt.Color(153, 153, 255));
        Enroll1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Enroll1.setForeground(new java.awt.Color(255, 255, 255));
        Enroll1.setText("View Enrolled Courses");
        Enroll1.setBorderPainted(false);
        Enroll1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Enroll1ActionPerformed(evt);
            }
        });

        contentPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        Logout.setBackground(new java.awt.Color(204, 204, 204));
        Logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Logout.setForeground(new java.awt.Color(102, 102, 255));
        Logout.setText("logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ViewCourses1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(Enroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Enroll1, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 262, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logout)
                .addGap(18, 18, 18)
                .addComponent(ViewCourses1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Enroll, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Enroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnrollActionPerformed
        cardLayout.show(contentPanel, "enroll");
    }//GEN-LAST:event_EnrollActionPerformed

    private void ViewCourses1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCourses1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "available");
    }//GEN-LAST:event_ViewCourses1ActionPerformed

    private void Enroll1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Enroll1ActionPerformed
        // TODO add your handling code here:
        cardLayout.show(contentPanel, "enrolled");
    }//GEN-LAST:event_Enroll1ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to logout?", "Confirm Logout",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            new LoginFrame(new UserService(dbManager)).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public void showPanel(String panelName) {
        cardLayout.show(contentPanel, panelName);
    }

    private void initCards() {
        cardLayout = (CardLayout) contentPanel.getLayout();

        
        if (courseService == null) {
            courseService = new CourseService(dbManager);
        }

        
        AvailableCourses availableCoursesPanel = new AvailableCourses(dbManager, studentId, this);
        EnrollCourse enrollCoursePanel = new EnrollCourse(dbManager, studentId, this);
        EnrolledCourses enrolledCoursesPanel = new EnrolledCourses(this);
        ////Lessons accessLessonPanel = new Lessons(this, courseService,studentService);
         QuizPanel quizPanel = getQuizPanel();

       
        LessonContent lessonContentPanel = new LessonContent(this, courseService, studentService);

        // Add to contentPanel
        contentPanel.add(availableCoursesPanel, "available");
        contentPanel.add(enrollCoursePanel, "enroll");
        contentPanel.add(enrolledCoursesPanel, "enrolled");
      //  contentPanel.add(accessLessonPanel, "lessons");
        contentPanel.add(lessonContentPanel, "lessonContent");
        contentPanel.add(quizPanel, "quiz");

        cardLayout.show(contentPanel, "available");
    }

    public StudentService getStudentService() {
        return this.studentService;
    }

    public JPanel getContentPanel() {
        return contentPanel;
    }

    public LessonContent getLessonContentPanel() {
        
        if (lessonContentPanel == null) {
            if (courseService == null) {
                courseService = new CourseService(dbManager);
            }
            lessonContentPanel = new LessonContent(this, courseService, studentService);

            
            contentPanel.add(lessonContentPanel, "lessonContent");
        }
        return lessonContentPanel;
    }
    
    public Lessons getLessonPanel(String courseId){
        if (LessonPanel == null) {
         if (courseService == null) {
                courseService = new CourseService(dbManager);
            }
         
            LessonPanel = new Lessons(this, courseService, studentService,courseId);
            contentPanel.add(LessonPanel, "lesson");
        }else {
             LessonPanel.loadlessons(courseId);
        }
            return LessonPanel;
            
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
 /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDashboard().setVisible(true); 
            }
        }); */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Enroll;
    private javax.swing.JButton Enroll1;
    private javax.swing.JButton Logout;
    private javax.swing.JButton ViewCourses1;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

//lab8// 
    
    public JsonDatabaseManager getDbManager()
    {
        return this.dbManager;
    }
    
    public String getStudentId()
    {
        return this.studentId;
    }
    
  
    public QuizPanel getQuizPanel() {
    if (quizPanel == null) {
        quizPanel = new QuizPanel(this);
        contentPanel.add(quizPanel, "quiz");
    }
    return quizPanel;
}
    
}